### ISSUE TITLE
Running with django

### ISSUE THREAD

**Issue by Glueon** [joeyespo/pytest-watch#23]
There is an issue with pytest-watch running with django. I think it is related to the https://github.com/joeyespo/pytest-watch/issues/21 issue.

While developing a django project sometims I get `test database already exists` when using pytest-watch. I think it's because pytest-watch in some circumstances launches second py.test copy. So we need some sort of locking mechanism, because otherwise it's really hard to use.

**Comment by joeyespo** [comment]
Oh wow, that would be problematic. Thanks for opening the issue.

Tests should absolutely have the ability to be run in parallel though. I wonder if this particular symptom is a case of hard-coding the test database path when you should really be using a random temp file (or `sqlite:///:memory:`).

Would using one of those techniques fix the `test database already exists` problem?

**Comment by Glueon** [comment]
pytest-django automatically creates and gives names to databases. It supports xdist out of the box so maybe it understands that if tests run in parallel it should create several different databases.

But when you manually spin up two py.test instances in parallel it has zero knowledge about this, therefore it tries to create a  `django_pytest_1` db for the first test and fails because another py.test instance has already created it. xdist divides tests into groups and does not run the same one twice.

That's only my guess but I think that this unwapted py.test process duplication is a problem which can theoretically lead to all sorts of problems.

**Comment by joeyespo** [comment]
Nice, I didn't know pytest-django created databases that way. Thanks for clarifying that.

xdist also has the ability to run multiple subprocesses, so pytest-watch shouldn't have a problem with that either.

It seems like a low-level design flaw if running `py.test` twice causes the tests to fail. That's why I suggested creating a *fresh database* (as opposed to creating a "database" with a unique name *within* a database system), since it's analogous to an [Immutable Server](http://martinfowler.com/bliki/ImmutableServer.html).

As for pytest-watch, it's possible to patch the underlying problem by waiting for the previous test process to finish. But since I see that as a disadvantage (since the *full test suite* will be run each time you press "save"), I wonder if there's a middleground. Perhaps when a restart is detected, a "stop" signal can be sent to the existing test process, and then we wait for that process to stop before running the tests again.

What do you think about that approach?

**Comment by Glueon** [comment]
Isn't it possible to block pytest-watch from restarting if py-test dropped into the IPDB session or is running? Like we disussed earlier.

**Comment by ethanmcc** [comment]
I'm having a similar problem I think waiting for the initial test to respond to the stop signal would be sufficient, and more optimal than waiting for the entire suite to finish.

**Comment by joeyespo** [comment]
Merging this into the more general issue #36.

Thanks for your thoughts on this.
