### ISSUE TITLE
Tests directory name gets autocompleted

### ISSUE THREAD

**Issue by muraveill** [joeyespo/pytest-watch#48]
My project has a directory `tests` containing the unit tests I want to run with pytests. It also has a directory `tests_functional`, which I don't want to run continuously.

    py.test tests/

will run only my unit tests, while

    ptw tests/

will also run everything in `tests_functional`, even so:

    ﻿ptw --ignore ./tests_functional ./tests

I don't see any way to run only what is in the `tests` folder. Moreover, I would expect a pytest extension to gather tests the same way pytest (and `pytest-xdist`) does.

**Comment by joeyespo** [comment]
Ok, so it turns out this worked as implemented. But since the CLI is misleading about what `--ignore` does, and that running `ptw --ignore tests_functional -- --ignore tests_functional` is way too verbose, I'm looking into improving this.

In the next release, you should be able to do what you did an expect it to ignore `tests_functional` in both the `pytest-watch` observer and in `py.test`.

Thanks for pointing out this awkward design!

**Comment by joeyespo** [comment]
Just published v4.0, which forwards all `--ignore` arguments to pytest.

After running `pip install --upgrade pytest-watch`, you should be able to run

```bash
$ ptw --ignore ./tests_functional
```

and have it work as expected (ptw doesn't watch that directory and pytest doesn't collect tests from it either). Thanks again!

**Comment by muraveill** [comment]
It works perfectly now, thanks!
