### ISSUE TITLE
Cannot specify excluded directory patterns

### ISSUE THREAD

**Issue by poulter7** [joeyespo/pytest-watch#6]
If possible I'd like to add a new flag to pytest-watch --nowatchdirs, which matches up with the naming of --norecursedirs, in pytest.

I've been looking at http://hypothesis.readthedocs.org/en/latest/, a quickcheck tool, which automatically generates random inputs to test functions to ultimately make more robust software, part of its processing involves creating modules on-the-fly. Hypothesis creates modules on the fly at the root of the main pytest running process and therefore pytest-watch picks up on the new modules as they are created and pytest-watch never stops.

If I could include:
--nowatchdirs ".hypothesis"

This would allow for such operation. Do you have any thoughts?

**Comment by joeyespo** [comment]
Ah yeah, something like this would be a good addition.

Do you think there's any value in separating out pytest's `--norecursedirs` to its own dedicated `--nowatchdirs` in pytest-watch?

What I mean is, wouldn't you want to exclude directories from both pytest and pytest-watch? If so, perhaps using the same name is appropriate: add a `--norecursedirs` argument to this project that both forwards it to pytest and tells pytest-watch to exclude those directories from the watch.

That logic could go one step further to handle any special cases too. After implementing #8, you could handle all three cases (note that these cases are possible by going with `--nowatchdirs`):
- `ptw --norecursedirs dir` to ignore from both
- `ptw -- --norecursedirs dir` to ignore from pytest only, but still be watched
- `ptw --norecursedirs dir -- --norecursedirs -` to ignore from the watch only, since the that argument is "overridden" by the argument passed to pytest (letting `-` mean "none")

Does that make sense? What do you think?

Thanks for opening the issue, @poulter7!

**Comment by aldanor** [comment]
@poulter7 Fixed in #11!

**Comment by joeyespo** [comment]
Went with @aldanor's solution with `--ignore`. Thanks for the issue, @poulter7.

**Comment by joeyespo** [comment]
FYI Released pytest-watch 3.0.0 today, which includes `--ignore`.
