### ISSUE TITLE
pytest-watch -- tests/specificfile.py

### ISSUE THREAD

**Issue by peterbe** [joeyespo/pytest-watch#70]
Things like `ptw {some ptw options}` works. Also do `ptw {some ptw options} -- -x` and this latter becomes the same as `pytest -x`. 

But I want to test just a specific file. Without ptw it would be `pytest tests/test_specificfile.py` and that'll ignore `tests/otherfile.py` etc. 

But this doesn't work: `ptw {some ptw options} -- tests/test_specificfile.py` :(

**Comment by blueyed** [comment]
Cannot reproduce.
`ptw -c -- ./test/test_foo.py` works for me.

**Comment by joeyespo** [comment]
I can't reproduce either. I just tried both `ptw -c -- ./tests/test.py` and `ptw -c -- tests/test.py`, since `./` is omitted the description's example.

@peterbe Can you copy/paste here the exact command you're running and its output? Also, does `ptw -- ./tests/test_specificfile.py` work for you? Are you running `ptw` in the right directory?

**Comment by peterbe** [comment]
Arrh! What the heck?! Now it's working for me too. I lost my bash history (docker) so I can't go back and see what I did. 
I think I had a bunch more options switch on and blinded myself by the simplest thing. Sorry for the distress.
