### ISSUE TITLE
-v doesn't seem to work properly

### ISSUE THREAD

**Issue by xmo-odoo** [joeyespo/pytest-watch#88]
In pytest, amongst other things `-v` shows fully qualified names for every test (and their status) instead of just a single-letter mark. This does not seem to work for pytest-watch, `ptw -v` still only shows the short marks.

**Comment by xmo-odoo** [comment]
> I don't think -v is a pytest-watch flag.

It's not, but I'd have expected ptw to either error or forward to pytest on unknown arguments.

**Comment by grantbachman** [comment]
Yes, it seems to me the correct behavior is to err on unknown arguments. And the double dash to forward to pytest should probably be documented inside of `--help`.

**Comment by joeyespo** [comment]
Thanks for jumping in, @grantbachman!

Yeah, this is expected behavior today. It does show `--` in the help, and does fail on unknown arguments, but I agree this could all be made more obvious.

My first thought was to deprecate `-v` and then remove it to avoid some of the confusion, but I think #57 ultimately covers this kind of problem more completely. So I'll close this in favor of that.

If `ptw -- -v` is having a problem, feel free to re-open with more detail about that case.

Thanks!
